<?php
function socialpanels_ctools_plugin_directory($owner, $plugin_type) {
	if ($owner == 'ctools' && $plugin_type == 'content_types') {
		return 'plugins/' . $plugin_type;
	}
}

function socialpanels_menu() {
	$items = array();
	$items['admin/config/socialpanels/defaults'] = array(
		'title' => t('Social Panels Pane default settings'),
		'description' => t('Set default values for Social Pane settings.'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('socialpanels_defaults'),
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM,
		);
	return $items;
}

function socialpanels_defaults() {
	$form['sp_twitterWidgetId'] = array(
		'#type' => 'textfield',
		'#title' => t('Twitter Widget ID'),
    	'#description' => t('You must <a href="https://twitter.com/settings/widgets">first create a Widget</a> from your account.'),
    	'#default_value' => variable_get('sp_twitterWidgetId'),
  	);
	$form['sp_fbappId'] = array(
		'#type' => 'textfield',
		'#title' => t('Facebook App Id'),
	    '#description' => t('You must <a href="https://developers.facebook.com">first create a Facebook App</a>.'),
	    '#default_value' => variable_get('sp_fbappId'),
	);
	return system_settings_form($form);
}

function socialpanels_uninstall() {
	variable_del('sp_twitterWidgetId');
	variable_del('sp_fbappId');
}